version: 0.2

env:
  variables:
    hugo_version: '0.74.3'

phases:
  install:
    commands:
      - cd /tmp
      - curl -Ls "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.deb" -o hugo.deb
      - dpkg -i hugo.deb
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - hugo
artifacts:
  files:
    - public/**/*
